moved all configs and such to ~/.dotfiler
Groctel/dotfiles-manager pull request #2
Opened 2020-09-17 19:35 UTC by QuartzShard

Moved config files and file storage to a folder in $HOME rather than wherever you happen to run dotfiler from.

2020-09-17 20:18 UTC, Groctel requested changes
In general, I like the idea behind this contribution.
I think having all your list files in a single directory can be positive for the structure of the dotfiles repository, but storing them in a place external to that repository would create an awful mess for the programmers and the users. Tracking dotfiles' dotfiles is a fun concept to entertain and the program can be made to check `./.dotfiler` before `./` and then even be passed a `--dir="path"` flag, but storing the list files outside the dotfiles directory would necessarily mean that the user would have to manually import them to let them be tracked in their repository, and that's a big anti-feature.

If you re-think the contribution to let the program check the directories as above (or other better structure you can propose) I'll happily merge it!

2020-09-17 20:18 UTC, Groctel commented on dotfiler.sh
> +
Why is it necessary to have the program perform an action that can be done manually by the user with (I believe) better results? I originally thought of doing this but I decided not to implement this function because I preferred the user to take their time in writing their filelist file first and then calling the program. What arguments do you have in favour of this implementation?
If this function is finally added the editor opening block should be its own function to avoid code repetition. It should also take the system tag as an argument.

2020-09-17 20:18 UTC, Groctel commented on dotfiler.sh
> +[ ! -n "$(find $confDir -maxdepth 1 -name 'filelist*' -print -quit)" ] && CreateFileList
Same as with the init function, I'd prefer this block to test a non negated statement and then execute if `false`.
Find is an overkill here, you can just use `-f`:

```sh
[ -f "$conf_dir"/filelist* ] || CreateFilelist
```

And you can also supress the potential error message with an explicit subshell:

```sh
( [ -f "$conf_dir"/filelist* ] ) 2>/dev/null || CreateFilelist
```

In case this function is added, this call should be in the inner while loop when checking for different system tags so that every tag is checked against this condition.

2020-09-17 20:54 UTC, QuartzShard commented on dotfiler.sh
> +[ ! -d "$confDir/files/" ] && mkdir "$HOME/.dotfiler/files"
`$confDir/files` gets populated when `./dotfiler -p` is run, rather than it creating a "files" directory wherever it is run and populating that. Made more sense to me that way

2020-09-17 20:55 UTC, QuartzShard commented on dotfiler.sh
> +
I agree. This is over-compensation for the fact that I'm usually bad at commenting

2020-09-17 20:56 UTC, QuartzShard commented on dotfiler.sh
> +
I found it a little unintuitive that there was no prompt to create a file list upon first use. This function is only called if there is no filelist, so would only be shown to a user who hasn't configured the script before running it

2020-09-17 20:57 UTC, QuartzShard commented on dotfiler.sh
> +[ ! -n "$(find $confDir -maxdepth 1 -name 'filelist*' -print -quit)" ] && CreateFileList
I just wrote something that worked if I'm honest, that seems a much better way to do this! I am not that well versed in bash scripting

2020-09-17 21:00 UTC, QuartzShard commented
To be honest, I didn't like the behaviour of just dumping the file lists to wherever dotfiler was and wrote in behaviour that made sense to me. If the direction i've gone in isn't what you want for the program, feel free to close the PR or edit it to suit the changes.
I'm still fairly new to the Linux ecosystem and this is the first time I've contributed to someone else's work, so I'm pleasantly surprised by the amount of polite, constructive criticism you've come back with.
Either way, If you think this would be worth merging with the alterations you've suggested I can clean up, just let me know!

2020-09-18 07:51 UTC, Groctel commented
I was a bit worried because I thought I had been a bit too hars, I'm glad I wasn't!

There are two idead in this PR that I like: Prompting the user to create the filelist file (or even remove it from the systems array) if it doesn't exist and giving the user the chance to declutter the repo's root directory by letting them store all items in a directory.
The first one is good but I think it should prompt the user to create the file, abort or ignore the system tag instead of forcingly opening the editor, which I believe would be more disruptive than helpful. The second one I like too as long as the path isn't hardcoded and can be set by the user.

Since you're new to Linux and open source contributions, I think it would be a positive experience for you to edit this PR yourself and have it finally accepted, but I understand that my vision of the program can be different from yours, so I wouldn't see it illogical that you close it and let me push the changes by myself, but they wouldn't be signed by you. Since you're the only PR I'm reviewing right now and I have spare time, I can personally help you write the contribution and answer your questions about Linux. Email me or send me a Reddit PM if you want!

2020-09-18 07:56 UTC, Groctel commented on dotfiler.sh
> +
I'm starting to follow [Uncle Bob](https://en.wikipedia.org/wiki/Robert_C._Martin)'s commenting principle:

> Comments are a last resort to use when the programmer has failed to communicate their intent with the code itself.

Since shell arguments are awfully numbered and I wanted to avoid the clutter and overhead of assigning variables to every single argument, I preferred to write the functions comments to have them be at least readable. I'm considering changing them now to make the code less cluttered, so don't worry about your commenting abilities, it's a difficult art to feel perfectly confident about.

2020-09-18 08:09 UTC, Groctel commented on dotfiler.sh
> +
If this function call is prompted in the main function it would be a nice adition, but I don't want to have it open forcibly. Here are my proposals for this function:

- Have it take the appropriate `$systag` as an argument so that it can create many files in one run.
- Change the `Confirm` text to explicit the system tag.
- Isolate the duplicate editor block in another function that takes the system tag.
- Preemptively `touch` the filelist file before editting it so later functions don't fail to open it.
- Remove the return portion of the comment block because the editor's exit code isn't being checked by other functions, so this function can be considered to return `void`.

2020-09-18 08:18 UTC, Groctel commented on dotfiler.sh
> +[ ! -n "$(find $confDir -maxdepth 1 -name 'filelist*' -print -quit)" ] && CreateFileList
It's ok. Shell scripting is a bit ugly and hard to learn in some ways but a POSIX compliant script will work in any system no matter what.

As I said in the general comment, `CreateFileList` (or maybe `CreateFilelist`?) should not be called directly if no filelist file is found but be prompted to the user with an option to create it, another to skip this file for the rest of the execution and another to abort the execution entirely.
Since it should be located in the inner block to check every system tag's filelist file, the proposed block should be a function of its own. I would have it echo the new state of `$systems` and change `$local_systems` accordingly. It's a bit tricky, but it can be made to work with some cleverness!

2020-09-18 08:22 UTC, Groctel commented on dotfiler.sh
> +[ ! -d "$confDir/files/" ] && mkdir "$HOME/.dotfiler/files"
Is your intended behaviour that no matter where the program is called from, the working directory (where the files are pulled and stored) should be the same? I'm a bit lost with this block and need clarification before discussing it further.

2020-09-22 08:14 UTC, Groctel requested changes
I'm not sure how you want the `$conf_dir` to work. Please explain it so I can better review this. Thanks!

2020-09-22 08:14 UTC, Groctel commented on dotfiler.sh
> +		[ -d "$conf_dir/files$current_systag/" ] || mkdir -p "$conf_dir/files$current_systag" #Create files directory
Since this operation is only relevant to `Pull`, it should me moved to that function. The comments should be removed and the files directory is created there, so the `mkdir -p` line should also be removed. This operation is not relevant to `Deploy` because creating a missing files directory there is a futile operation, so it should just return an error. I've also noticed that files are being pulled to `$conf_dir` here and in many other lines. Is relocating the pulled dotfiles' location the purpose of this PR? I had understood different and don't know what you're trying to do here.

2020-09-22 08:14 UTC, Groctel commented on dotfiler.sh
> +		"${EDITOR:-vi}" "$conf_dir/filelist$1"
While letting the user use their default `$EDITOR` first is brilliant, it should be checked in case `vi` doesn't exist so that the user can specify their own `$EDITOR`.

2020-09-22 08:14 UTC, Groctel commented on dotfiler.sh
> +			[ "$line" = '' ] && break
Instead of a `break` statement, the lines below should be encapsulated in their own block. This should be changed to the following:

```sh
[ "$line" != "" ] && {
   # ...
}
```

2020-10-25 15:18 UTC, Groctel commented
After giving some thought to this PR while it was inactive I've realised I don't want to merge these functions. Thanks for your contribution and time.

2020-10-25 15:18 UTC, closed without merging